baseURL = "/"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
title = "Sociedade Vegana"
theme = "sk1"

SectionPagesMenu = "main"
Paginate = 300
googleAnalytics = "UA-22147311-21"
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."